--- #YAML:1.0
name:                Test-URI
version:             1.06
abstract:            Check Uniform Resource Identifiers
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Test::Builder::Tester:         0
    Test::More:                    0
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
